version: "3.3"

services:
  db:
    image: mysql:5.7.29
    volumes:
      - plugin_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4.0-php7.2-apache
    ports:
      - "4000:80"
    volumes:
      - ./wp-data/:/var/www/html
      - ./sendgrid-subscribe-button/:/var/www/html/wp-content/plugins/sendgrid-subscribe-button
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  plugin_data: {}
